# Generated by Django 5.2.8 on 2025-12-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instruction",
            field=models.CharField(default=""),
        ),
    ]
