# Generated by Django 5.2.8 on 2025-12-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_description_recipe_instruction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="created_by",
        ),
        migrations.AddField(
            model_name="user",
            name="saved",
            field=models.ManyToManyField(related_name="sigma", to="recipe.recipe"),
        ),
    ]
