# Generated by Django 5.2.8 on 2025-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_remove_recipe_created_by_user_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
