# Generated by Django 6.0 on 2025-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_recipe_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instruction",
            field=models.TextField(default=""),
        ),
    ]
